// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARo4zULdlJsD35pMl95r_9-He9B7DPbjo',
    appId: '1:604195004739:web:19126f55bf057230498ff6',
    messagingSenderId: '604195004739',
    projectId: 'chat-app-51103',
    authDomain: 'chat-app-51103.firebaseapp.com',
    storageBucket: 'chat-app-51103.appspot.com',
    measurementId: 'G-DC5JTX8PRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5668owR60ljnDV61a3n-lN9DX4xqY2oc',
    appId: '1:604195004739:android:59026a60e9d93236498ff6',
    messagingSenderId: '604195004739',
    projectId: 'chat-app-51103',
    storageBucket: 'chat-app-51103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4C-LnYfKTOimr9coTFEL_qyHQWpf1PAY',
    appId: '1:604195004739:ios:dc592222c9fc4bd1498ff6',
    messagingSenderId: '604195004739',
    projectId: 'chat-app-51103',
    storageBucket: 'chat-app-51103.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4C-LnYfKTOimr9coTFEL_qyHQWpf1PAY',
    appId: '1:604195004739:ios:b8dfeebd0f3148a8498ff6',
    messagingSenderId: '604195004739',
    projectId: 'chat-app-51103',
    storageBucket: 'chat-app-51103.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
